codes:
  - "RAPT4.SA"
  - "MRFG3.SA"
  - "USIM5.SA"
  - "TIMP3.SA"
  - "RUMO3.SA"
  - "POMO4.SA"
  - "ITSA4.SA"
  - "GOLL4.SA"
  - "GOAU4.SA"
  - "GFSA3.SA"
  - "EVEN3.SA"
  - "ELPL4.SA"
  - "ECOR3.SA"
  - "DTEX3.SA"
  - "CYRE3.SA"
  - "CMIG4.SA"
  - "BRPR3.SA"
