codes:
  - "RAPT4.SA"
  - "MRFG3.SA"
  - "USIM5.SA"
  - "TIMP3.SA"
  - "RUMO3.SA"
  - "POMO4.SA"
  - "ITSA4.SA"
  - "GOLL4.SA"
  - "GOAU4.SA"
  - "GFSA3.SA"
  - "EVEN3.SA"
  - "ELPL4.SA"
  - "ECOR3.SA"
  - "DTEX3.SA"
  - "CYRE3.SA"
  - "CMIG4.SA"
  - "BRPR3.SA"
  - "ABEV3.SA"
  - "ALSC3.SA"
  - "ANIM3.SA"
  - "BBAS3.SA"
  - "BBDC3.SA"
  - "BBDC4.SA"
  - "BBSE3.SA"
  - "BEEF3.SA"
  - "BRAP4.SA"
  - "BRFS3.SA"
  - "BRML3.SA"
  - "BTOW3.SA"
  - "BVMF3.SA"
  - "CCRO3.SA"
  - "CESP6.SA"
  - "CIEL3.SA"
  - "CMIG4.SA"
  - "CPFE3.SA"
  - "CPLE6.SA"
  - "CSAN3.SA"
  - "CSNA3.SA"
  - "CTIP3.SA"
  - "CYRE3.SA"
  - "DTEX3.SA"
  - "ECOR3.SA"
  - "ELET3.SA"
  - "ELET6.SA"
  - "ELPL4.SA"
  - "EMBR3.SA"
  - "ENBR3.SA"
  - "EQTL3.SA"
  - "ESTC3.SA"
  - "FIBR3.SA"
  - "GFSA3.SA"
  - "GGBR4.SA"
  - "GOAU4.SA"
  - "GOLL4.SA"
  - "GRND3.SA"
  - "HGTX3.SA"
  - "HYPE3.SA"
  - "IGTA3.SA"
  - "ITSA4.SA"
  - "ITUB4.SA"
  - "JBSS3.SA"
  - "KROT3.SA"
  - "LAME3.SA"
  - "LAME4.SA"
  - "LIGT3.SA"
  - "LINX3.SA"
  - "LREN3.SA"
  - "MDIA3.SA"
  - "MGLU3.SA"
  - "MPLU3.SA"
  - "MRVE3.SA"
  - "MULT3.SA"
  - "MYPK3.SA"
  - "NATU3.SA"
  - "ODPV3.SA"
  - "PCAR4.SA"
  - "PDGR3.SA"
  - "PETR3.SA"
  - "PETR4.SA"
  - "POMO4.SA"
  - "PSSA3.SA"
  - "QGEP3.SA"
  - "QUAL3.SA"
  - "RADL3.SA"
  - "RENT3.SA"
  - "RUMO3.SA"
  - "SBSP3.SA"
  - "SEER3.SA"
  - "SMLE3.SA"
  - "SMTO3.SA"
  - "SULA11.SA"
  - "SUZB5.SA"
  - "VALE3.SA"
  - "VALE5.SA"
    #  - "SANB11.SA"
    #  - "TAEE11.SA"
    #  - "TBLE3.SA"
    #- "TIET11.SA"
    #- "TIMP3.SA"
    #- "TOTS3.SA"
    #- "TRPL4.SA"
    #- "UGPA3.SA"
    #- "VIVT4.SA"
    #- "VLID3.SA"
    #- "VVAR11.SA"
    #  - "KLBN11.SA"
    #- "WEGE3.SA"
